[package]
name = "swww-daemon"
version = "0.9.5-masterV2"
authors = ["Leonardo Gibrowski Faé <leonardo.fae44@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", default_features = false, features = [ "max_level_debug", "release_max_level_info", "std" ] }

rustix = { version = "0.38", default-features = false, features = [ "event" ] }
libc = "0.2"

keyframe = "1.1"

sd-notify = { version = "0.4.1" }

utils = { version = "0.9.5-masterV2", path = "../utils" }
