[package]
name = "swww-daemon"
version = "0.9.5-master"
authors = ["Leonardo Gibrowski Faé <leonardo.fae44@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", default_features = false, features = ["max_level_debug", "release_max_level_info", "std"] }

wayland-client = { version = "0.31", default-features = false, features = [ "log" ]}
wayland-protocols = { version = "0.31", default-features = false, features = [ "client", "staging" ]}
wayland-protocols-wlr = { version = "0.2", default-features = false, features = [ "client" ]}

rustix = { version = "0.38", default-features = false, features = [ "event" ] }
libc = "0.2"

keyframe = "1.1"
spin_sleep = "1.2"

sd-notify = { version = "0.4.1" }

utils = { version = "0.9.5-master", path = "../utils" }
[dev-dependencies]
rand = "0.8"
