[package]
name = "utils"
version = "0.8.2-master"
authors = ["Leonardo Gibrowski Faé <leonardo.fae44@gmail.com>"]
edition = "2021"
license-file = "../LICENSE"

[dependencies]
rkyv = "0.7"

[build-dependencies]
pkg-config = "0.3"

[dev-dependencies]
rand = "0.8"
criterion = "0.5"

[[bench]]
name = "compression"
harness = false
